backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: post
    label: Post
    folder: content/posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: youtube, label: Youtube Link }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
